excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://mintpresso.github.io
title: ZARI Developers
email: zari.devops@gmail.com
author: Jinhyuk Lee
description: ZARI Developers
paginate: 5
google_analytics: 
