excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://mintpresso.github.io
title: Awesome
email: jhlee@yellotravel.com
author: mintpresso
description: My awesome new site
paginate: 3
google_analytics: 